backube/snapscheduler

- pkg/controller/snapshotschedule/snapshotschedule_controller.go
- pkg/controller/snapshotschedule/snapshotschedule_test.go
> Expire snapshots by time

- pkg/controller/snapshotschedule/snapshots_expire.go
- pkg/controller/snapshotschedule/snapshots_expire_test.go
- pkg/controller/snapshotschedule/snapshotschedule_controller.go
- pkg/controller/snapshotschedule/snapshotschedule_test.go
> Expire by count

- README.md
- deploy/crds/snapscheduler_v1alpha1_snapshotschedule_cr.yaml
- deploy/role.yaml
- docs/_config.yml
- docs/index.md
- docs/install.md
- docs/readme.md
- docs/usage.md
> Install & usage documentation

- Makefile
> Fix setting operator version during build

- .codecov.yml
- pkg/controller/snapshotschedule/snapshotschedule_controller.go
- pkg/controller/snapshotschedule/snapshotschedule_test.go
> Properly truncate names when building snapshot name

- deploy/operator.yaml
> Set replica:2 & resource requests

- README.md
- cmd/manager/main.go
- pkg/apis/addtoscheme_snapscheduler_v1alpha1.go
- pkg/apis/apis.go
- pkg/apis/snapscheduler/group.go
- pkg/apis/snapscheduler/v1alpha1/doc.go
- pkg/apis/snapscheduler/v1alpha1/register.go
- pkg/apis/snapscheduler/v1alpha1/snapshotschedule_types.go
- pkg/controller/add_snapshotschedule.go
- pkg/controller/controller.go
- pkg/controller/snapshotschedule/snapshots_expire.go
- pkg/controller/snapshotschedule/snapshots_expire_test.go
- pkg/controller/snapshotschedule/snapshotschedule_controller.go
- pkg/controller/snapshotschedule/snapshotschedule_test.go
- tools.go
- version/version.go
> License update

- pkg/controller/snapshotschedule/snapshots_expire_test.go
- pkg/controller/snapshotschedule/snapshotschedule_test.go
> Add test for listPVCsMatchingSelector

- CHANGELOG.md
- README.md
- SECURITY.md
- docs/_config.yml
> Housekeeping for pre release

- .travis.yml
- .travis/yamlconfig.yaml
- Makefile
- helm/snapscheduler/.helmignore
- helm/snapscheduler/Chart.yaml
- helm/snapscheduler/README.md
- helm/snapscheduler/crds/snapscheduler.backube_snapshotschedules_crd.yaml
- helm/snapscheduler/templates/NOTES.txt
- helm/snapscheduler/templates/_helpers.tpl
- helm/snapscheduler/templates/deployment.yaml
- helm/snapscheduler/templates/role.yaml
- helm/snapscheduler/templates/rolebinding.yaml
- helm/snapscheduler/templates/serviceaccount.yaml
- helm/snapscheduler/values.yaml
> Add helm chart

- docs/install.md
- helm/snapscheduler/Chart.yaml
- Update docs to encourage use of chart
- Update chart to v1.0.0 and set it to deploy v1.0.0 of the scheduler
> Create chart v1.0.0

- README.md
Adds badge to readme for fossa license scan
Closes #44
> Add badge for fossa

- README.md
> Replace Travis w/ GH action badge

- SECURITY.md
- docs/usage.md
Doc update describing the use of ResourceQuotas
Fixes #59
> Document use of ResourceQuota to limit snapshots

- .ci-scripts/tests/test-simple-schedule.sh
- .github/workflows/tests.yml
- hack/setup-kind-cluster.sh
Cleanup the mess in the GH action workflow
> CI cleanup

- .github/workflows/tests.yml
- Makefile
Upgrade golangci-lint to v1.23.1
Fixes #67
> Upgrade golangci-lint to v1.23.1

- hack/run-in-kind.sh
Add helper script for running locally
> Add helper script for running locally

- .github/workflows/tests.yml
- Makefile
Upgrade golangci-lint to 1.23.3
> Upgrade golangci-lint to 1.23.3

- docs/Gemfile.lock
- docs/development.md
* Docs for running e2e just like CI.
* How to use the `hack` scripts to get a cluster for testing
> Add documentation for E2E testing

- .ci-scripts/pre-commit.sh
- .ci-scripts/yamlconfig.yaml
- deploy/crds/snapscheduler.backube_v1_snapshotschedule_cr.yaml
- deploy/olm-catalog/csv-config.yaml
- deploy/olm-catalog/snapscheduler/1.1.0/snapscheduler.v1.1.0.clusterserviceversion.yaml
- deploy/olm-catalog/snapscheduler/1.1.0/snapshotschedules.snapscheduler.backube.crd.yaml
- deploy/olm-catalog/snapscheduler/snapscheduler.package.yaml
- helm/snapscheduler/README.md
This adds the CSV and other files necessary to deploy snapscheduler w/ OLM
Related to #14
> Add files to deploy w/ OLM

- hack/setup-kind-cluster.sh
The deploy script for the hostpath driver changed names, so CI was failing. This updates to the new name.
Also cleans up some whitespace.
Fixes #91
> Fix hostpath deployment for CI

- CHANGELOG.md
- docs/index.md
- helm/snapscheduler/Chart.yaml
Update docs, helm chart, CHANGELOG for release 1.1.1
> Prepare for release v1.1.1

- helm/snapscheduler/Chart.yaml
- helm/snapscheduler/README.md
This is to release the fix for min kube version to allow pre-release
versions to be ok.
Prepare for release to include #98 since it is being hit (#100)
> Update Helm chart to v1.2.1

- .github/workflows/tests.yml
Enables CodeQL scanning of source
> Add CodeQL to GH actions

- README.md
The old readme wasn't very inviting. This re-works it as a "quickstart" so users can figure out what it does more easily.
> Rework README w/ quickstart

- .github/workflows/tests.yml
- Fixes configuration of codecov action
- Makes the action triggers more selective so as not to cause duplicate runs
> GH action updates

- Dockerfile
- Makefile
The operator version wasn't properly being set in the operator executable
> Fix version in operator logs

- test-kuttl/e2e/multi-pvc/10-waitfor-snapshot.yaml
- test-kuttl/kuttl-test.yaml
Makes yet another try at fixng this flaky test
#127
> Rework checking for expected snaps in multi-pvc test

- Makefile
Bump versions of helm, operator-sdk, and kuttl
> Update helm, osdk, kuttl versions

- config/manager/manager.yaml
- helm/snapscheduler/README.md
- helm/snapscheduler/templates/deployment.yaml
- helm/snapscheduler/values.yaml
If we run w/ multiple replicas, we should try to put them on different nodes.
> Add anti-affinity for the operator pods

- CHANGELOG.md
- helm/snapscheduler/Chart.yaml
- release-checklist.md
Final updates for release of v2
> Updates for v2 release

- bundle.Dockerfile
- bundle/manifests/snapscheduler-controller-manager-metrics-service_v1_service.yaml
- bundle/manifests/snapscheduler-controller-manager_v1_serviceaccount.yaml
- bundle/manifests/snapscheduler-manager-config_v1_configmap.yaml
- bundle/manifests/snapscheduler-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/snapscheduler.backube_snapshotschedules.yaml
- bundle/manifests/snapscheduler.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- release-checklist.md
Adds the operator bundle for v2.0.0 that is being submitted to operatorhub
> Add operator bundle for version 2.0.0

- config/crd/bases/snapscheduler.backube_snapshotschedules.yaml
- config/rbac/role.yaml
- go.mod
- hack/run-in-kind.sh
- hack/setup-kind-cluster.sh
- helm/snapscheduler/crds/snapscheduler.backube_snapshotschedules.yaml
- main.go
- test-kuttl/e2e/custom-snapclass/00-create-workload.yaml
- test-kuttl/e2e/label-selector-equality/00-create-workload.yaml
- test-kuttl/e2e/label-selector-set/00-create-workload.yaml
- test-kuttl/e2e/metrics/00-check-metrics.yaml
- test-kuttl/e2e/minimal-schedule/00-create-workload.yaml
- test-kuttl/e2e/multi-pvc/00-create-workload.yaml
- test-kuttl/e2e/template-labels/00-create-workload.yaml
> Update autogenerated files caused by controller-gen upgrade

- .github/workflows/tests.yml
- hack/setup-kind-cluster.sh
> Update KinD to 0.12.0

- bundle/manifests/snapscheduler.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manifests/bases/snapscheduler.clusterserviceversion.yaml
- release-checklist.md
Looks like we also need the annotation in the bundle in addition to the minVersion in the CSV
> Add annotation for min OpenShift version

- .github/dependabot.yml
- .github/workflows/tests.yml
- Enables dependabot for version updates
- Switches GH actions to use sha versions for better security
> Enable dependbot updates

- Makefile
- bundle.Dockerfile
- bundle/manifests/snapscheduler.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
> Update to operator-sdk 1.20

- Makefile
- bundle.Dockerfile
- bundle/manifests/snapscheduler.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
> Update to operator-sdk v1.21.0

- .github/workflows/stale.yml
> Add stale action to close neglected PRs

- CHANGELOG.md
- bundle/manifests/snapscheduler.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- helm/snapscheduler/Chart.yaml
- helm/snapscheduler/values.yaml
> Update kube-rbac-proxy to v0.13.0

- Makefile
- hack/run-in-kind.sh
- hack/test-full.sh
- test-kuttl/e2e/custom-snapclass/00-create-workload.yaml
- test-kuttl/e2e/custom-snapclass/9999-delete-ns.yaml
- test-kuttl/e2e/label-selector-equality/00-create-workload.yaml
- test-kuttl/e2e/label-selector-equality/9999-delete-ns.yaml
- test-kuttl/e2e/label-selector-set/00-create-workload.yaml
- test-kuttl/e2e/label-selector-set/9999-delete-ns.yaml
- test-kuttl/e2e/metrics/00-assert.yaml
- test-kuttl/e2e/metrics/00-check-metrics.yaml
- test-kuttl/e2e/metrics/9999-delete-ns.yaml
- test-kuttl/e2e/minimal-schedule/00-create-workload.yaml
- test-kuttl/e2e/minimal-schedule/9999-delete-ns.yaml
- test-kuttl/e2e/multi-pvc/00-create-workload.yaml
- test-kuttl/e2e/multi-pvc/9999-delete-ns.yaml
- test-kuttl/e2e/template-labels/00-create-workload.yaml
- test-kuttl/e2e/template-labels/9999-delete-ns.yaml
Updates tests to more closely align w/ "restricted" profile
We still don't set the `seccompProfile` since this will break on OpenShift
> Psa compliance

- hack/setup-kind-cluster.sh
> Update to csi-hostpath 1.9 & enable fsGroup

- CHANGELOG.md
- bundle/manifests/snapscheduler.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- docs/index.md
- helm/snapscheduler/Chart.yaml
> Prep for release v3.1

- .github/workflows/periodic.yml
> tests: fix syntax in periodic job

- CHANGELOG.md
- config/default/manager_auth_proxy_patch.yaml
- helm/snapscheduler/Chart.yaml
- helm/snapscheduler/values.yaml
* Updates kube-rbac-proxy to latest released version
* Updates Changelogs
> Update quay.io/brancz/kube-rbac-proxy to v0.13.1

- .github/workflows/periodic.yml
- release-checklist.md
Enables periodic builds of:
- release-3.2 branch
- v3.2.0 tag
> tests: Enable periodic builds of v3.2.0

- .github/workflows/periodic.yml
- .github/workflows/stale.yml
- .github/workflows/tests.yml
> Annotate GH actions versions

- renovate.json
> Renovate: go mod tidy when updating modules

- renovate.json
- renovate.json5
> Apply migration to renovate config

- .ci-scripts/yamlconfig.yaml
> Ignore problems w/ yaml comments in workflow files

- .github/workflows/tests.yml
> Clean pre-commit cache

- renovate.json5
> Allow renovate to update dependency lock files

- renovate.json5
> Disable semantic commits in renovate

- renovate.json5
> Attempt to get renovate to update docker images in yamls

- renovate.json5
> Adjust renovate on only run in the morning on weekdays

- hack/setup-kind-cluster.sh
- renovate.json5
- Disable update/pinning of scorecard, snapscheduler images
- Ignore the fake "controller" image
- Configure autoupdate of hostpath and snapshotter in the kind script
> Update renovate configuration

- renovate.json5
> Only update renovate's pre-commit hooks weekly

- renovate.json5
> Don't pin docker image hashes

- .pre-commit-config.yaml
> Upgrade markdownlint to v0.13.0

- .github/workflows/tests.yml
- hack/setup-kind-cluster.sh
> CI: Add kube 1.29 to test matrix

- renovate.json5
> Ensure all golang version upgrades are batched

- renovate.json5
Signed-off-by: John Strunk <jstrunk@redhat.com>
> Group GH actions updates & fix golang grouping

- .github/workflows/tests.yml
Also adds ruby fix for markdownlint
- #726
> Update to ubuntu v24

- bundle/manifests/snapscheduler.backube_snapshotschedules.yaml
- bundle/manifests/snapscheduler.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Update the OLM bundle files for 3.5.0
