backube/snapscheduler

deploy/crds/snapscheduler_v1alpha1_snapshotschedule_crd.yaml, pkg/apis/snapscheduler/v1alpha1/snapshotschedule_types.go
```
$ kubectl get snapshotschedule/example-hourly
NAME             SCHEDULE    MAX AGE   MAX NUM   DISABLED   NEXT SNAPSHOT
example-hourly   0 * * * *   168h      10                   2019-10-30T21:00:00Z
```
Fixes #2
=> Add addl print cols for snapshotschedule

helm/snapscheduler/Chart.yaml
Github won't serve SVG by default unless sanitize=true is passed in the
url. This tells it to remove embedded javascript.
Updates chart to 1.0.1
=> Add sanitize parameter to icon url

deploy/role.yaml, helm/snapscheduler/Chart.yaml, helm/snapscheduler/templates/role.yaml
The operator didn't have permission to watch() v1.PVC. While the
operator code doesn't directly create such a watch, it is happening in
client-go. This adds the permission to the ClusterRole for the operator.
Also bumps the chart version since it's a change to the chart.
Fixes #55
=> Fix Failed to watch *v1.PersistentVolumeClaim

.github/workflows/tests.yml
Tests have been flaky due to failures of apt-get when installing
prereqs. This adds a few retries to see if that helps.
=> Add retries to install in tests

go.mod, go.sum
The external snapshotter w/ v2.0.1 has properly set up go modules, so we
no longer need the import hack.
Fixes #68
=> Remove external snapshotter import hack

CHANGELOG.md
Switch changelog to today's date for v1.1.0 release
=> Correct release date in changelog

CHANGELOG.md, pkg/controller/snapshotschedule/snapshotschedule_controller.go
The snapshotTemplate is meant to be optional (if no labels are provided and the default snapclass name should be used). That case was not properly handled, resulting in a nil dereference.
Fixes #80
=> Properly handle nil snapshot template

docs/usage.md
Adds documentation to clarify that the cronspec is interpreted in the UTC timezone
Fixes #83
=> Document schedules are relative to UTC

.github/workflows/tests.yml, hack/setup-kind-cluster.sh
Adds kube 1.18.0 to CI test matrix
Fixes #87
=> Add 1.18 to list of kube versions in CI

.github/workflows/tests.yml, Makefile, hack/setup-kind-cluster.sh, helm/snapscheduler/Chart.yaml, helm/snapscheduler/README.md, helm/snapscheduler/templates/NOTES.txt, helm/snapscheduler/templates/deployment.yaml, helm/snapscheduler/values.yaml
Updates the helm chart to:
- Print the chart and operator (image tag) version when installing
- Default to having a node selector for amd64/linux nodes since we don't build multi-arch images
Fixes #75
Fixes #78
=> Helm updates

helm/snapscheduler/Chart.yaml
The previous `kubeVersion` semver in the Helm chart incorrectly disallowed installation on prerelease Kubernetes versions. This change makes prerelease versions ok.
=> Change helm min kube version to allow prerelease kube

.github/workflows/tests.yml, docs/index.md
Adds kube 1.19 to the CI test matrix and updates older kube versions to latest z release (that's available for kind).
=> Add kube 1.19 to test matrix

.github/workflows/tests.yml, hack/setup-kind-cluster.sh
- Updates external-snapshotter to v3 for 1.17+ test clusters
- Updates kind to latest (0.9.0)
=> Update external-snapshotter to v3.0.0

.github/workflows/tests.yml, hack/setup-kind-cluster.sh
- Fixes CI for 1.17+ due to release of snapshot controller
- Adds 1.20 to test matrix
=> Include kube 1.20 in CI

hack/setup-kind-cluster.sh, helm/snapscheduler/templates/deployment.yaml
Previously, the chart created a Service for metrics, but the port didn't match that of the metrics endpoint in the operator Deployment.
This adds the metrics port to the list of container ports and updates the Service to connect to it.
Fixes #116
=> Fix metrics service

README.md
Fixes the link to the Helm chart in Artifact Hub
=> Fix artifact hub link in readme

config/manager/kustomization.yaml, test-kuttl/e2e/multi-pvc/10-waitfor-snapshot.yaml
The multi-pvc test has been failing frequently in CI, but passes locally. This increases the timeout to give the GH runner a bit more time.
=> Increase timeout from multi-pvc e2e

.github/workflows/tests.yml, hack/run-in-kind.sh, helm/snapscheduler/templates/clusterrole-metrics-reader.yaml, helm/snapscheduler/templates/clusterrole-proxy.yaml, helm/snapscheduler/templates/deployment.yaml, helm/snapscheduler/templates/rolebinding-proxy.yaml, helm/snapscheduler/templates/service-metrics.yaml, helm/snapscheduler/values.yaml, test-kuttl/e2e/metrics/00-assert.yaml, test-kuttl/e2e/metrics/00-check-metrics.yaml
Adds an option to the Helm chart to disable authentication of the `/metrics` endpoint.
=> Add chart option to disable metrics auth

.github/workflows/tests.yml
The GH action permissions have been set to restrictive. This change grants necessary permissions so that the CodeQL job can run
=> Add permissions for so codeql passes w/ restricted gh action permissions

.github/workflows/tests.yml, Makefile, go.mod
Add the `actions/cache` gh action to cache go modules so that downloading/setup is quicker
Currently, w/o caching, the "build" step takes ~5m.
=> Add cache action to speed build step

.github/workflows/tests.yml, Dockerfile, Makefile, docs/index.md, go.mod, go.sum, hack/setup-kind-cluster.sh
- Updates to go 1.18
- Adds kube 1.24 to test matrix
- Updates utilities (helm, kind, kuttl, golangci-lint)
=> Update to go 1.18 & kube 1.24

hack/setup-kind-cluster.sh
Deploy external-snapshotter v6 for kube 1.24+ clusters
=> Move kind to snapshotter v6 for 1.24+

docs/Gemfile, docs/Gemfile.lock
- Removes some unnecessary Gem dependencies for building on windows
- Removal permits updating activesupport to fix vulnerabilities
=> Remove unnecessary doc dependencies

config/crd/bases/snapscheduler.backube_snapshotschedules.yaml, helm/snapscheduler/crds/snapscheduler.backube_snapshotschedules.yaml
Allows for ranges and slash notations.
Signed-off-by: Wolfgang Jentner <10183885+wjentner@users.noreply.github.com>
Updates the RegEx evaluating the cron syntax to be more permissive, such that ranges and slash notations are allowed.
The `@every` syntax is not working in the current implementation, it is therefore removed from the RegEx.
Related: #229
=> Update cron-regex in CRD to be more permissive

.github/workflows/periodic.yml, .github/workflows/tests.yml
Moves the periodic triggering of builds on master to a separate workflow file so that we can also trigger release branches and tag rebuilds (eventually).
=> tests: Add periodic job to trigger other workflows

CHANGELOG.md, helm/snapscheduler/Chart.yaml, helm/snapscheduler/README.md, helm/snapscheduler/templates/_helpers.tpl, helm/snapscheduler/templates/deployment.yaml, helm/snapscheduler/values.yaml
Adds a `.image` field to the chart's values file so that a full container image w/ hash can be specified
Fixes #252
=> helm: Allow specifying containers by sha hash

CHANGELOG.md, Makefile, api/v1/snapshotschedule_types.go, config/crd/bases/snapscheduler.backube_snapshotschedules.yaml, helm/snapscheduler/Chart.yaml, helm/snapscheduler/README.md, helm/snapscheduler/crds/snapscheduler.backube_snapshotschedules.yaml, helm/snapscheduler/templates/snapscheduler.backube_snapshotschedules.yaml, helm/snapscheduler/values.yaml
Moves the CRDs to be treated as normal templates in the chart so that they can be installed, upgraded, and removed as appropriate so that they stay in sync with the operator.
NOTE: This is a breaking change for users upgrading from v3.1.0 or earlier. They will need to manually annotate/label the CRDs in order for the upgrade to succeed.
Fixes #253
=> Helm: Make the chart manage CRDs

.github/workflows/periodic.yml
Due to the mdl breaking change, we cannot do container rebuilds for this tag.
=> CI: Disable rebuilds of tagged 3.2.0

helm/snapscheduler/templates/deployment.yaml, helm/snapscheduler/values.yaml
Introduces the option to set a priorityClassName for the deployment on Kubernetes
No, this PR does not change the default behavior (= no priorityClassName set)
Compare the output of these command:
- Default behavior: `helm template .`
- PriorityClassName set: `helm template --set=priorityClassName=system-cluster-critical .`
issue #347
=> Helm chart: Option to set a priorityClassName

Makefile
Fixes `docker-buildx` target. I'm not sure why this parameter was left out. If I generate a Makefile with Operator SDK, it is present.
=> fix: docker buildx takes a single parameter: the directory

helm/snapscheduler/Chart.yaml, helm/snapscheduler/README.md, helm/snapscheduler/templates/deployment.yaml, helm/snapscheduler/values.yaml
Adds support for adding additional pod labels and annotations to the snapscheduler pod.  Adding key value pairs to the `podLabels` and `podAnnotations` variables will add them to the template's deployment spec.
N/A
closes #157
=> Support for pod labels and annotations

.github/workflows/tests.yml, docs/index.md, hack/setup-kind-cluster.sh
- Update kind to v0.20.0
- Adds kube 1.27 & 1.28 to the test matrix
- Upgrades external snapshotter to v6.2.2
=> Update kind to v0.20.0

test-kuttl/e2e/metrics/00-check-metrics.yaml
Switches to a fedora image and from wget to curl to test the metrics endpoint
For some reason, wget is unable to negotiate the TLS connection to the rbac proxy container. curl has no problem though.
=> Switch to fedora for e2e metrics test

helm/snapscheduler/templates/deployment.yaml, helm/snapscheduler/templates/role-leader-election.yaml, helm/snapscheduler/templates/rolebinding-leader-election.yaml, helm/snapscheduler/templates/service-metrics.yaml, helm/snapscheduler/templates/serviceaccount.yaml
This MR adds the `metadata.namespace` value to all namespaced Kubernetes resources.
While this is a common practice seen in most public helm charts, my particular desire for this change is to enable deploying this chart via [ArgoCD](https://argo-cd.readthedocs.io/en/stable/).
Without this change I see the following ArgoCD errors
Whereas with the change, I see successful syncs
It's more typical to see `{{ .Release.Namespace | quote }}` used. However, I chose not to use this because this chart already has examples of using just `{{ .Release.Namespace }}`: https://github.com/backube/snapscheduler/blob/v3.3.0/helm/snapscheduler/templates/rolebinding.yaml#L10
=> Add `metadata.namespace` to Kubernetes resources

hack/setup-kind-cluster.sh
Starting w/ v8, the external snapshotter only supports back to 1.25
Signed-off-by: John Strunk <jstrunk@redhat.com>
=> Upgrade external snapshotter to v8
